---
# Install the collections using:
# ansible-galaxy collection install -p collections -r ./requirements/collections.yml
collections:
  - name: nixknight.docker
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/docker,docker-0.1.1"
  - name: nixknight.opentofu
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/opentofu,opentofu-0.1.3"
  - name: nixknight.general
    type: git
    source: "git+https://github.com/NIXKnight/Ansible-Collections.git#/collections/nixknight/general,main"
